#+TITLE: Conforguration
#+AUTHOR: William Denton
#+EMAIL: wtd@pobox.com

#+PROPERTY: header-args :var script_dir="conforguration_scripts", dotfiles_dir="dotfiles"

This has my dotfiles and helper scripts to install R from source.

If you're looking at this on GitHub, the BEGIN and END source block wrappers are hidden, so you can't see the parameters.  Look at the raw version of the file, or clone the repository and load it into Emacs, to read it properly.

* Initialize

Make the ~conforguration_scripts/~ and ~dotfiles/~ directories on this machine.  (Doing this at the start is easier than using ~:mkdirp yes~ on the tangled blocks.)

#+BEGIN_SRC shell :results silent
mkdir -p $script_dir
mkdir -p $dotfiles_dir
#+END_SRC

* Setup: Dotfiles

Dotfiles are stored in ~dotfiles/~ in raw form, not tangled in Org (perhaps this will come later).  The setup script, that symlinks everything, is also in there.

If you need some special environment variables on a machine, put them in ~.bash.$HOSTNAME.rc~, as described at the bottom of ~.bashrc~.  That's one way of setting up private environment variables that hold passwords or API tokens.

#+BEGIN_SRC shell :tangle dotfiles/dotfile-setup.sh :shebang "#!/bin/sh" :eval no
DOTFILES=".[a-zA-Z]*"
for DOTFILE in $DOTFILES; do
  rm -f ~/${DOTFILE}
  ln -s ~/$dotfiles_dir/${DOTFILE} ~/${DOTFILE}
done
rm ~/.profile
ln -s ~/.bash_profile ~/.profile
#+END_SRC

#+RESULTS:

#+BEGIN_SRC shell :results output
ls -al $dotfiles_dir
#+END_SRC

#+RESULTS:
#+begin_example
total 144
drwxr-xr-x 2 wdenton wdenton  4096 Oct 13 12:37 .
drwxr-xr-x 5 wdenton wdenton  4096 Oct 13 12:37 ..
-rw------- 1 wdenton wdenton   121 May 30 10:43 .bash_logout
-rw------- 1 wdenton wdenton    42 May 30 10:31 .bash_profile
-rw-r--r-- 1 wdenton wdenton  6028 Sep 23 11:47 .bashrc
-rw------- 1 wdenton wdenton 10242 May 11 10:05 .dircolors.ansi-dark
-rwxr-xr-x 1 wdenton wdenton   242 Oct 13 12:37 dotfile-setup.sh
-rw------- 1 wdenton wdenton   118 May 30 12:45 .gemrc
-rw------- 1 wdenton wdenton 57491 May 11 10:05 .git-completion.bash
-rw------- 1 wdenton wdenton   424 May 16 09:55 .gitconfig
-rw------- 1 wdenton wdenton 14374 May 16 09:55 .lynxrc
-rw------- 1 wdenton wdenton    71 May 11 16:48 .nanorc
-rw------- 1 wdenton wdenton   818 May 11 12:00 .Rprofile
-rw-r--r-- 1 wdenton wdenton   112 Oct 13 12:34 .rubocop.yml
-rw------- 1 wdenton wdenton    84 May 30 10:31 .signature
-rw------- 1 wdenton wdenton  1332 May 11 13:50 .tmux.conf
#+end_example

* Setup: R

** Requirements

PATH needs to include ~/usr/local/src/R~, but my ~bashrc~ has that configured already.

The first line of requirements may be needed for R 3.3.  The ~topicmodels~ package requires the GNU Scientific Library.  Once done, this doesn't need to be run again.  Sync and run the script on machines as necessary.

#+BEGIN_SRC shell :tangle conforguration_scripts/r-install-requirements.sh :shebang "#!/bin/bash"
sudo apt-get install libbz2-dev liblzma-dev libpcre3-dev fonts-inconsolata
sudo apt-get install xorg-dev gfortran libreadline-dev libcurl4-openssl-dev libssl-dev
sudo apt-get build-dep r-base
sudo apt-get install libgsl-dev
mkdir -p ~/R/history/
mkdir -p /usr/local/src/R
#+END_SRC

** Installing

Change the version number as needed.

#+NAME: R_VERSION
| 3.3.2 |

#+BEGIN_SRC shell :tangle conforguration_scripts/r-install-from-source.sh :shebang "#!/bin/bash" :var R_VERSION=R_VERSION
cd /usr/local/src/R
curl -O https://cran.hafro.is/src/base/R-3/R-$R_VERSION.tar.gz
tar xzvf R-$R_VERSION.tar.gz
cd R-$R_VERSION
./configure
make && make check
cd ..
rm R Rscript
ln -s R-$R_VERSION/bin/R R
ln -s R-$R_VERSION/bin/Rscript Rscript
PACKAGE_LIST="dplyr readr tidyr ggplot2 devtools roxygen2 lubridate shiny knitr ggvis seriation igraph arules arulesViz tm wordcloud cluster fpc topicmodels"
for PKG in $PACKAGE_LIST; do ./Rscript --vanilla -e "install.packages('$PKG', repos=c('https://cran.hafro.is/'))"; done
./Rscript --vanilla -e "devtools::install_github('rstudio/shinyapps')"
#+END_SRC

* Setup: Ruby

** Requirements

#+BEGIN_SRC shell :tangle conforguration_scripts/ruby-install-requirements.sh :shebang "#!/bin/bash"
sudo apt-get build-dep ruby
#+END_SRC

** Installation

Change the version number as needed.

TODO: Don't delete =rbenv=, skip cloning it if it's already there.

#+NAME: RUBY_VERSION
| 2.3.3 |

#+BEGIN_SRC shell :tangle conforguration_scripts/ruby-install-from-source.sh :shebang "#!/bin/bash" :var RUBY_VERSION=RUBY_VERSION
rm -rf ~/.rbenv/
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
source ~/.bashrc
rbenv install --verbose $RUBY_VERSION
rbenv global $RUBY_VERSION
gem install marc nokogiri sqlite3 rubocop backup bundler jekyll t
echo "Now run bundler install where needed."
#+END_SRC

* Machines

** localhost

*** Dotfiles

#+BEGIN_SRC shell :results output
cp -r dotfiles ~/
cd ~/dotfiles/
./dotfile-setup.sh
#+END_SRC

#+RESULTS:

** music

*** Dotfiles

#+BEGIN_SRC shell :results silent
rsync -avz --times $dotfiles_dir/ music:$dotfiles_dir/
#+END_SRC

#+BEGIN_SRC shell :dir /music:dotfiles/ :results output
./dotfile-setup.sh
#+END_SRC

#+RESULTS:

** pair

*** Dotfiles

#+BEGIN_SRC shell :results silent
rsync -avz --times $dotfiles_dir/ pair:$dotfiles_dir/
#+END_SRC

#+BEGIN_SRC shell :dir /pair:dotfiles/ :results output
./dotfile-setup.sh
#+END_SRC

#+RESULTS:

** shell

*** Dotfiles

#+BEGIN_SRC shell :results silent
rsync -avz --times $dotfiles_dir/ shell:$dotfiles_dir/
#+END_SRC

#+BEGIN_SRC shell :dir /shell:dotfiles/ :results output
./dotfile-setup.sh
#+END_SRC

#+RESULTS:

** ares

*** Dotfiles

#+BEGIN_SRC shell :results silent
rsync -avz --times $dotfiles_dir/ ares:$dotfiles_dir/
#+END_SRC

#+BEGIN_SRC shell :dir /ares:dotfiles/ :results output
./dotfile-setup.sh
#+END_SRC

#+RESULTS:

*** Synchronize install scripts

#+BEGIN_SRC shell :results silent
rsync -avz --times $script_dir/ ares:$script_dir/
#+END_SRC

*** Install

#+BEGIN_SRC shell :dir /ares:conforguration_scripts/ :results silent
./r-install-from-source.sh
#+END_SRC

** vm1

*** Dotfiles

#+BEGIN_SRC shell :results silent
rsync -avz --times $dotfiles_dir/ vm1:$dotfiles_dir/
#+END_SRC

#+BEGIN_SRC shell :dir /vm1:dotfiles/ :results output
./dotfile-setup.sh
#+END_SRC

#+RESULTS:

*** Synchronize install scripts

#+BEGIN_SRC shell :results silent
rsync -avz --times $script_dir/ vm1:$script_dir/
#+END_SRC

*** Install

#+BEGIN_SRC shell :dir /vm1:conforguration_scripts/ :results silent
./r-install-from-source.sh
#+END_SRC

#+RESULTS:

** wdenton

*** Dotfiles

#+BEGIN_SRC shell :results silent
rsync -avz --times $dotfiles_dir/ wdenton:$dotfiles_dir/
#+END_SRC

#+BEGIN_SRC shell :dir /wdenton:dotfiles/ :results output
./dotfile-setup.sh
#+END_SRC

#+RESULTS:

*** Synchronize install scripts

#+BEGIN_SRC shell :results silent
rsync -avz --times $script_dir/ wdenton:$script_dir/
#+END_SRC

*** Install

#+BEGIN_SRC shell :dir /wdenton:conforguration_scripts/ :results silent
./r-install-from-source.sh
#+END_SRC

#+RESULTS:
