#+TITLE: Conforguration
#+AUTHOR: William Denton
#+EMAIL: wtd@pobox.com

#+PROPERTY: header-args :var script_dir="conforguration_scripts", dotfiles_dir="dotfiles"

This has my dotfiles and helper scripts to install R from source.

If you're looking at this on GitHub, the BEGIN and END source block wrappers are hidden, so you can't see the parameters.  Look at the raw version of the file, or clone the repository and load it into Emacs, to read it properly.

* Initialize

Make the ~conforguration_scripts/~ and ~dotfiles/~ directories on this machine.  (Doing this at the start is easier than using ~:mkdirp yes~ on the tangled blocks.)

#+BEGIN_SRC shell :results silent
mkdir -p $script_dir
mkdir -p $dotfiles_dir
#+END_SRC

* Setup: Dotfiles

Dotfiles are stored in ~dotfiles/~ in raw form, not tangled in Org (perhaps this will come later).  The setup script, that symlinks everything, is also in there.

If you need some special environment variables on a machine, put them in ~.bash.env.$HOSTNAME.sh~, as described at the bottom of ~.bashrc~.  That's one way of setting up private environment variables that hold passwords or API tokens.

#+BEGIN_SRC shell :tangle dotfiles/dotfile-setup.sh :shebang "#!/bin/sh" :eval no
DOTFILES=".[a-zA-Z]*"
for DOTFILE in $DOTFILES; do
  rm -f ~/${DOTFILE}
  ln -s ~/$dotfiles_dir/${DOTFILE} ~/${DOTFILE}
done
#+END_SRC

#+RESULTS:

#+BEGIN_SRC shell :results output
ls -al $dotfiles_dir
#+END_SRC

#+RESULTS:
: total 148
: drwxr-xr-x 2 wtd wtd  4096 May 10 09:46 .
: drwxr-xr-x 5 wtd wtd  4096 May 10 09:52 ..
: -rwxr-xr-x 1 wtd wtd  5895 May  9 19:56 .bashrc
: -rw-r--r-- 1 wtd wtd 10242 May  9 19:56 .dircolors.ansi-dark
: -rwxr-xr-x 1 wtd wtd   195 May 10 09:46 dotfile-setup.sh
: -rw-r--r-- 1 wtd wtd   118 May  9 19:56 .gemrc
: -rw-r--r-- 1 wtd wtd 57491 May  9 19:56 .git-completion.bash
: -rwxr-xr-x 1 wtd wtd    41 May  9 19:56 .profile

* Setup: R

** Requirements

PATH needs to include ~/usr/local/src/R~, but my ~bashrc~ has that configured already.

The first line of requirements may be needed for R 3.3.  The ~topicmodels~ package requires the GNU Scientific Library.  Once done, this doesn't need to be run again.  Sync and run the script on machines as necessary.

#+BEGIN_SRC shell :tangle conforguration_scripts/r-install-requirements.sh :shebang "#!/bin/bash"
sudo apt-get install libbz2-dev liblzma-dev libpcre3-dev fonts-inconsolata
sudo apt-get install libgsl0-dev
#+END_SRC

** Installing

Change the version number as needed.

#+NAME: RVERSION
| 3.3.0 |

#+BEGIN_SRC shell :tangle conforguration_scripts/r-install-from-source.sh :shebang "#!/bin/bash" :var RVERSION=RVERSION
cd /usr/local/src/R
curl -O http://cran.utstat.utoronto.ca/src/base/R-3/R-$RVERSION.tar.gz
tar xzvf R-$RVERSION.tar.gz
cd R-$RVERSION
./configure
make && make check
cd ..
rm R Rscript
ln -s R-$RVERSION/bin/R R
ln -s R-$RVERSION/bin/Rscript Rscript
PACKAGE_LIST="dplyr readr tidyr ggplot2 devtools lubridate shiny knitr ggvis seriation igraph arules arulesViz tm wordcloud cluster fpc topicmodels"
for PKG in $PACKAGE_LIST; do ./Rscript --vanilla -e "install.packages('$PKG', repos=c('https://cran.hafro.is/'))"; done
./Rscript --vanilla -e "devtools::install_github('rstudio/shinyapps')"
#+END_SRC

* Machines

** localhost

*** Dotfiles

#+BEGIN_SRC shell :results output
cp -r dotfiles ~/
cd ~/dotfiles/
./dotfile-setup.sh
#+END_SRC

#+RESULTS:

** music

*** Dotfiles

#+BEGIN_SRC shell :results output
rsync -avz --times $dotfiles_dir/ music:$dotfiles_dir/
#+END_SRC

#+RESULTS:
: sending incremental file list
: ./
: .bashrc
: dotfile-setup.sh
:
: sent 423 bytes  received 117 bytes  216.00 bytes/sec
: total size is 73,974  speedup is 136.99

#+BEGIN_SRC shell :dir /music:dotfiles/ :results output
./dotfile-setup.sh
#+END_SRC

#+RESULTS:

** pair

*** Dotfiles

#+BEGIN_SRC shell :results output
rsync -avz --times $dotfiles_dir/ pair:$dotfiles_dir/
#+END_SRC

#+RESULTS:
: sending incremental file list
: ./
: .bashrc
: dotfile-setup.sh
:
: sent 423 bytes  received 117 bytes  216.00 bytes/sec
: total size is 73,974  speedup is 136.99

#+BEGIN_SRC shell :dir /pair:dotfiles/ :results output
./dotfile-setup.sh
#+END_SRC

#+RESULTS:

** shell

*** Dotfiles

#+BEGIN_SRC shell :results output
rsync -avz --times $dotfiles_dir/ shell:$dotfiles_dir/
#+END_SRC

#+RESULTS:
: sending incremental file list
: ./
: .bashrc
: dotfile-setup.sh
:
: sent 387 bytes  received 120 bytes  338.00 bytes/sec
: total size is 73,974  speedup is 145.91

#+BEGIN_SRC shell :dir /shell:dotfiles/ :results output
./dotfile-setup.sh
#+END_SRC

#+RESULTS:

** vm1

*** Dotfiles

#+BEGIN_SRC shell :results output
rsync -avz --times $dotfiles_dir/ vm1:$dotfiles_dir/
#+END_SRC

#+RESULTS:
: sending incremental file list
: ./
: .bashrc
: dotfile-setup.sh
:
: sent 423 bytes  received 117 bytes  360.00 bytes/sec
: total size is 73,974  speedup is 136.99

#+BEGIN_SRC shell :dir /vm1:dotfiles/ :results output
./dotfile-setup.sh
#+END_SRC

#+RESULTS:

*** Synchronize install scripts

#+BEGIN_SRC shell :results silent
rsync -avz --times $script_dir/ vm1:$script_dir/
#+END_SRC

*** Install

#+BEGIN_SRC shell :dir /vm1:conforguration_scripts/ :results output
./r-install-from-source.sh
#+END_SRC

#+RESULTS:

** wdenton

*** Dotfiles

#+BEGIN_SRC shell :results output
rsync -avz --times $dotfiles_dir/ wdenton:$dotfiles_dir/
#+END_SRC

#+RESULTS:
: sending incremental file list
: ./
: .bashrc
: dotfile-setup.sh
:
: sent 423 bytes  received 117 bytes  360.00 bytes/sec
: total size is 73,974  speedup is 136.99

#+BEGIN_SRC shell :dir /wdenton:dotfiles/ :results output
./dotfile-setup.sh
#+END_SRC

#+RESULTS:

*** Synchronize install scripts

#+BEGIN_SRC shell :results silent
rsync -avz --times $script_dir/ wdenton:$script_dir/
#+END_SRC

*** Install

#+BEGIN_SRC shell :dir /wdenton:conforguration_scripts/ :results output
./r-install-from-source.sh
#+END_SRC

#+RESULTS:
