#+TITLE: Conforguration
#+AUTHOR: William Denton
#+EMAIL: wtd@pobox.com

This is a short example of using Org to configure a machine to download and compile [[https://r-project.org/][R]] from source, in ~/usr/local/src/R/~, arrange symlinks so there will be a constant path to the binary across version changes, install a set of preferred packages, and if necessary edit your ~/.bashrc~ so that your $PATH is proper.

If you're looking at this on GitHub, the BEGIN and END source block wrappers are hidden, so you can't see the parameters.  Look at the raw version of the file, or clone the repository and load it into Emacs, to read it properly.

* Initialize

Make the ~scripts/~ directory on this machine.  (Doing this at the start is easier than using ~:mkdirp yes~ on the tangled blocks.)

#+BEGIN_SRC shell :results silent
mkdir -p scripts
#+END_SRC

* Setup: Dotfiles

Dotfiles are stored in ~dotfiles/~ in raw form, not tangled in Org (perhaps this will come later),

However, the setup script, that symlinks everything, is kept here for easy editing.

#+BEGIN_SRC shell :tangle dotfiles/dotfile-setup.sh :shebang "#!/bin/sh" :eval no
DOTFILES="bashrc dircolors.ansi-dark gemrc git-completion.bash profile"
for DOTFILE in $DOTFILES; do
  rm -f ~/.${DOTFILE}
  ln -s ~/dotfiles/.${DOTFILE} ~/.${DOTFILE}
done
#+END_SRC

#+RESULTS:

#+BEGIN_SRC shell :results output
ls -al dotfiles/
#+END_SRC

#+RESULTS:
: total 148
: drwxr-xr-x 2 wtd wtd  4096 May  9 21:30 .
: drwxr-xr-x 5 wtd wtd  4096 May  9 21:30 ..
: -rwxr-xr-x 1 wtd wtd  5895 May  9 19:56 .bashrc
: -rw-r--r-- 1 wtd wtd 10242 May  9 19:56 .dircolors.ansi-dark
: -rwxr-xr-x 1 wtd wtd   183 May  9 21:30 dotfile-setup.sh
: -rw-r--r-- 1 wtd wtd   118 May  9 19:56 .gemrc
: -rw-r--r-- 1 wtd wtd 57491 May  9 19:56 .git-completion.bash
: -rwxr-xr-x 1 wtd wtd    41 May  9 19:56 .profile

Compile the dotfiles into a zip file, to make it easier to copy elsewhere.

#+BEGIN_SRC shell :results output
rm -f dotfiles.zip
zip -r dotfiles.zip dotfiles/
#+END_SRC

#+RESULTS:
:   adding: dotfiles/ (stored 0%)
:   adding: dotfiles/.bashrc (deflated 53%)
:   adding: dotfiles/.profile (stored 0%)
:   adding: dotfiles/.gemrc (deflated 21%)
:   adding: dotfiles/.dircolors.ansi-dark (deflated 64%)
:   adding: dotfiles/.git-completion.bash (deflated 72%)
:   adding: dotfiles/dotfile-setup.sh (deflated 28%)

* Setup: R

** Requirements

The first line of requirements may be needed for R 3.3.  The ~topicmodels~ package requires the GNU Scientific Library.  Once done, this doesn't need to be run again.  Sync and run the script on machines as necessary.

#+BEGIN_SRC shell :tangle scripts/r-install-requirements.sh :shebang "#!/bin/bash"
sudo apt-get install libbz2-dev liblzma-dev libpcre3-dev fonts-inconsolata
sudo apt-get install libgsl0-dev
#+END_SRC

** Set up PATH

#+BEGIN_SRC shell :tangle scripts/r-update-bashrc.sh :shebang "#!/bin/bash"
if ! [[ ":$PATH:" == *":/usr/local/src/R:"* ]]; then
  echo 'Adding /usr/local/src/R to $PATH'
  echo '# Running R from source in /usr/local/src/R' >> ~/.bashrc
  echo 'PATH=$PATH:/usr/local/src/R' >> ~/.bashrc
else
  echo "/usr/local/src/R is already in $PATH"
fi
#+END_SRC

** Installing

Change the version number on this script as needed.

#+BEGIN_SRC shell :tangle scripts/r-install-from-source.sh :shebang "#!/bin/bash"
cd /usr/local/src/R
VERSION=3.3.0
curl -O http://cran.utstat.utoronto.ca/src/base/R-3/R-$VERSION.tar.gz
tar xzvf R-$VERSION.tar.gz
cd R-$VERSION
./configure
make && make check
cd ..
rm R Rscript
ln -s R-$VERSION/bin/R R
ln -s R-$VERSION/bin/Rscript Rscript
PACKAGE_LIST="dplyr readr tidyr ggplot2 devtools lubridate shiny knitr ggvis seriation igraph arules arulesViz tm wordcloud cluster fpc topicmodels"
for PKG in $PACKAGE_LIST; do ./Rscript --vanilla -e "install.packages('$PKG', repos=c('https://cran.hafro.is/'))"; done
./Rscript --vanilla -e "devtools::install_github('rstudio/shinyapps')"
#+END_SRC

* Machines

** localhost (marcus)

*** Dotfiles

#+BEGIN_SRC shell :results output
cp -r dotfiles ~/
cd ~/dotfiles/
./dotfile-setup.sh
#+END_SRC

#+RESULTS:

** music

*** Dotfiles

#+BEGIN_SRC shell :results output
rsync -avz --times dotfiles.zip music:
#+END_SRC

#+RESULTS:
: sending incremental file list
: dotfiles.zip
:
: sent 3,254 bytes  received 449 bytes  1,058.00 bytes/sec
: total size is 24,089  speedup is 6.51

#+BEGIN_SRC shell :dir /music: :results output
unzip -o dotfiles.zip
cd dotfiles
./dotfile-setup.sh
#+END_SRC

#+RESULTS:
: Archive:  dotfiles.zip
:   inflating: dotfiles/.bashrc
:  extracting: dotfiles/.profile
:   inflating: dotfiles/.gemrc
:   inflating: dotfiles/.dircolors.ansi-dark
:   inflating: dotfiles/.git-completion.bash
:   inflating: dotfiles/dotfile-setup.sh

** pair

*** Dotfiles

#+BEGIN_SRC shell :results output
rsync -avz --times dotfiles.zip pair:
#+END_SRC

#+RESULTS:
: sending incremental file list
: dotfiles.zip
:
: sent 23,535 bytes  received 35 bytes  5,237.78 bytes/sec
: total size is 24,089  speedup is 1.02

#+BEGIN_SRC shell :dir /pair: :results output
unzip -o dotfiles.zip
cd dotfiles
./dotfile-setup.sh
#+END_SRC

#+RESULTS:
: Archive:  dotfiles.zip
:    creating: dotfiles/
:   inflating: dotfiles/.bashrc
:  extracting: dotfiles/.profile
:   inflating: dotfiles/.gemrc
:   inflating: dotfiles/.dircolors.ansi-dark
:   inflating: dotfiles/.git-completion.bash
:   inflating: dotfiles/dotfile-setup.sh

** vm1

*** Dotfiles

#+BEGIN_SRC shell :results output
rsync -avz --times dotfiles.zip vm1:
#+END_SRC

#+RESULTS:
: sending incremental file list
: dotfiles.zip
:
: sent 23,535 bytes  received 233 bytes  9,507.20 bytes/sec
: total size is 24,089  speedup is 1.01

#+BEGIN_SRC shell :dir /vm1: :results output
unzip -o dotfiles.zip
cd dotfiles
./dotfile-setup.sh
#+END_SRC

#+RESULTS:
: Archive:  dotfiles.zip
:    creating: dotfiles/
:   inflating: dotfiles/.bashrc
:  extracting: dotfiles/.profile
:   inflating: dotfiles/.gemrc
:   inflating: dotfiles/.dircolors.ansi-dark
:   inflating: dotfiles/.git-completion.bash
:   inflating: dotfiles/dotfile-setup.sh

*** Synchronize install scripts

This will synchronize the scripts to vm1, a server I run.  Other servers could be added.

#+BEGIN_SRC shell :results silent
rsync -avz --times scripts/ vm1:scripts/
#+END_SRC

*** Install

The best way to arrange actually running the scripts on the remote servers is probably to specify a section for each one and specify each script that will be run.

#+BEGIN_SRC shell :dir /vm1:scripts/ :results output
./r-install-from-source.sh
#+END_SRC

#+RESULTS:
