#+TITLE: Conforguration README
#+AUTHOR: William Denton
#+EMAIL: wtd@pobox.com

* Conforguration

Use the power of [[http://orgmode.org/][Org]] to configure accounts and servers.

* How does it work?

Everything is in [[file:conforguration.org][conforguration.org]].  Tangling that file (by running ~M-x org-babel-tangle~ or =C-c C-v t=) will generate all of the dot files and scripts.  Installing Conforguration copies these into =~/conforg/=:  dot files are in ~/conforg/dotfiles/~ and scripts (to install Emacs, R and Ruby) are in ~/conforg/scripts/~.  This =~/conforg/= directory can be pushed to remote machines.

There are two types of dot files:  "mine" (most of them) or "imported" (a few copied verbatim from elsewhere).  Symbolic links are made from your home directory to =~/conforg/dotfiles/=.

The scripts can be run locally or on remote machines.  Either locally or remotely, you can use ~C-c C-c~ on the shell blocks to execute them, or you can run the scripts at the command line.

* How to install Emacs from scratch the Conforguration way

Warning: this will overwrite all sorts of VERY IMPORTANT files, so you don't do this unless you're me, or you're on a new bare system and want to try it out.  (Work on Debian, Ubuntu and related systems.

#+BEGIN_SRC shell :eval no
cd
sudo apt-get install git
git clone git@github.com:wdenton/.emacs.d.git
mkdir -p src
cd src
git clone git@github.com:wdenton/conforguration.git
# Or if you don't want to use a GitHub account:
# git clone https://github.com/wdenton/conforguration.git
conforguration/install/install.sh
source ~/.bashrc
~/conforg/scripts/initialize.sh
~/conforg/scripts/emacs-install-requirements.sh
~/conforg/scripts/emacs-install-personal.sh
#+END_SRC

Then run =emacs=.  A few dozen packages will be downloaded and installed and when that's done your Emacs will look exactly like mine!  If you don't want to go that far, skip the =.emacs.d= repository download, but make sure your PATH is set up to point to Emacs in the right place under =/usr/local/src/=.

* Why?

Because [[https://www.ansible.com/][Ansible]] and similar configuration management tools aren't done in Org.

* What next?

I don't know, but if you're interested, have at it.

There are a lot of dot files in [[https://github.com/webpro/awesome-dotfiles][awesome-dotfiles]], and it seems [[https://github.com/aldrichtr/tangld][tangld]] is a similar project to this.  There will be things to be learned from any related projects.

* License

GPL v3.  See COPYING for details.
