#+TITLE: Conforguration README
#+AUTHOR: William Denton
#+EMAIL: wtd@pobox.com

# This is under the GPL v3.  See COPYING for details.

* Conforguration

Use the power of [[http://orgmode.org/][Org]] to configure accounts and servers.

* How does it work?

Run ~M-x org-babel-tangle~ (=C-c C-v t=) on [[file:conforguration.org][conforguration.org]] to generate installation scripts in the ~conforguration_scripts/~ and ~dotfiles/~ directories.

** Dotfiles

Raw dotfiles are in ~dotfiles/~. Because they start with a dot (e.g. ~.bashrc~) they are not visible to ~ls~ normally, so use ~ls -a~ to see them.

Dotfiles are copied to ~$HOME/dotfiles/~ and symlinks are made from your home directory to there.

** Installing applications and packages

Sync the scripts to remote servers, then run the scripts on those remote servers.  Or run them locally!

The nice things about this is that either locally or remotely, you can use ~C-c C-c~ on the shell blocks to execute them, or you can run the scripts at the command line.

* How to install Emacs from scratch the Conforguration way

Warning: this will overwrite all sorts of VERY IMPORTANT files, so you don't do this unless you're me, or you're on a new bare system and want to try it out.

#+BEGIN_SRC shell :eval no
cd
sudo apt-get install git
git clone git@github.com:wdenton/.emacs.d.git
mkdir -p src
cd src
git clone git@github.com:wdenton/conforguration.git
cd conforguration/dotfiles
./dotfile-setup.sh
source ~/.bashrc
cd ../scripts
./initialize.sh
./emacs-install-requirements.sh
./emacs-install-from-source.sh
#+END_SRC

Then run =emacs=.  A few dozen packages will be downloaded and installed and when that's done your Emacs will look exactly like mine!  If you don't want to go that far, skip the =.emacs.d= repository download, but make sure your PATH is set up to point to Emacs in the right place under =/usr/local/src/=.

* Why?

Because [[https://www.ansible.com/][Ansible]] and similar configuration management tools aren't done in Org.

* What next?

I don't know, but if you're interested, have at it.

There is a lot of duplication.  Perhaps there is a nice way to tidy that up.

* License

GPL v3.  See COPYING for details.
